### ISSUE TITLE
Show notes (home page)

### ISSUE THREAD

**Issue by tk-codes** [felixenchiparamban/wed2_testat#4]
- [x] noteController/showNotes
- [x] noteService/get
- [x] handle sort & filter parameters
- [x] render **views/index.hbs**

**Comment by felixenchiparamban** [comment]
## Style
-  [x] create Button
-  [x] set default style 
-  [x] shift edit button to right hand side
-  [x] radio button (delete) and insert tria.
-  [x] trigger points: 
  -  [x] 320px(mob first, screen)
  -  [x] 480px (screen)
  -  [x] 800px (screen)
  -  [x] from 800px (screen & print)
-  [x] hide finished notes / show all (with handlesbars)
-  [x] line 36: dateFormat (eliminate redundancy)
-  [x] isFinished(read only)
-  [x] line 38: isFinished (eliminate redundancy)
-  [x] css
  -  [x] 0 ohne masseinheit
  -  [x] common style (eliminate redundancy, use class/id, only colour, background colour, border colour in theme)
  -  [x] don't use "*"

## controller
-  [x] implement session
